# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Mario Soriano Jr."
#description: >- # this means to ignore newlines until "baseurl:"
#  Bay is a minimal Jekyll Theme.
baseurl: "/about" # the subpath of the site
url: "https://mariosorianojr.github.io" # the base hostname & protocol for the site
#og_image: /visuals/mario.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: mariojr.soriano@yale.edu
      link: mailto:mariojr.soriano@yale.edu

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
